kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
  namespace: demo-project
stringData:
  BACKEND_SECRET: averysecretpassword
  basedomain: apps.cluster-ht4gg.ht4gg.sandbox75.opentlc.com
type: Opaque