kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: demo-project
data:
  app-config-rhdh.yaml: |
    signInPage: oidc   
    app:
      title: My Red Hat Developer Hub Instance
      baseUrl: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
    backend:
      reading:
        allow:
          - host: raw.githubusercontent.com
          - host: github.com
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
      cors:
        origin: https://backstage-developer-hub-demo-project.${basedomain} # be aware: project 'demo-project' is part of the url. Change it if you use another project
    integrations:
      github:
        - host: github.com
          token: ${RHDH_GITHUB_INTEGRATION_PERSONAL_ACCESS_TOKEN}
          apps:
            - appId: ${RHDH_GITHUB_INTEGRATION_APP_ID}
              clientId: ${RHDH_GITHUB_INTEGRATION_APP_CLIENT_ID}
              clientSecret: ${RHDH_GITHUB_INTEGRATION_APP_CLIENT_SECRET}
              webhookUrl: none
              webhookSecret: none
              privateKey: ${RHDH_GITHUB_INTEGRATION_APP_PRIVATE_KEY}
    catalog:
      processingInterval: { minutes: 1 }
      processing:
        cache:
          enabled: false
      lifecycles:
        - production
        - staging
      rules:
        - allow: [Location, Component, API, Resource, System, Domain, Group, User, Template]
      locations: 
        - rules:
            - allow:
                - Group
                - User
                - Component
                - Location
                - System
                - Resource
                - Domain
                - API
                - Template
          target: https://github.com/maarten-vandeperre/developer-hub-documentation/blob/main/configurations/catalog-entities/all.yaml
          type: url
      providers:
        keycloakOrg:
          default:
            baseUrl: https://demo-keycloak-instance.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com
            loginRealm: rhdh # ${KEYCLOAK_REALM}
            realm: rhdh # ${KEYCLOAK_REALM}
            clientId: rhdh-client # ${KEYCLOAK_CLIENTID}
            clientSecret: 7iKyQUwyApIojzOlSj82vUWIhejv41E5 # ${KEYCLOAK_CLIENTSECRET}
            # highlight-add-start
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }
              initialDelay: { seconds: 15 }
              # highlight-add-end
        github:
          # the provider ID can be any camelCase string
          providerId:
            organization: 'maarten-vandeperre' # string
            catalogPath: '/catalog-info.yaml' # string
            filters:
              branch: 'master' # string
              repository: '.*' # Regex
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
        ocm:
          default:
            kubernetesPluginRef: local-cluster
            name: multiclusterhub
            owner: group:rhdh
            schedule:
              frequency:
                seconds: 10
              timeout:
                seconds: 60
        threeScaleApiEntity:
          default:
            baseUrl: https://demo-organization-admin.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com
            accessToken: f1dcf5f09fe82043da924386d58743bb291c42e12bfad58f35a834434e9562ad
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }
        #if-minio-techdocs-disabled awsS3: # minio
          #if-minio-techdocs-disabled default: # identifies your dataset / provider independent of config changes
            #if-minio-techdocs-disabled bucketName: minio-tech-docs
            #if-minio-techdocs-disabled #prefix: prefix/ # optional
            #if-minio-techdocs-disabled region: eu-west-3 # optional, uses the default region otherwise
            #if-minio-techdocs-disabled schedule: # same options as in TaskScheduleDefinition
              #if-minio-techdocs-disabled # supports cron, ISO duration, "human duration" as used in code
              #if-minio-techdocs-disabled #frequency: { minutes: 30 }
              #if-minio-techdocs-disabled frequency: { minutes: 1 }
              #if-minio-techdocs-disabled # supports ISO duration, "human duration" as used in code
              #if-minio-techdocs-disabled timeout: { minutes: 3 }
              #if-minio-techdocs-disabled initialDelay: { seconds: 15 }
        #if-aws-techdocs-disabled awsS3:
          #if-aws-techdocs-disabled default: # identifies your dataset / provider independent of config changes
            #if-aws-techdocs-disabled bucketName: redhat-demo-dev-hub-1
            #if-aws-techdocs-disabled #prefix: prefix/ # optional
            #if-aws-techdocs-disabled region: eu-west-3 # optional, uses the default region otherwise
            #if-aws-techdocs-disabled schedule: # same options as in TaskScheduleDefinition
              #if-aws-techdocs-disabled # supports cron, ISO duration, "human duration" as used in code
              #if-aws-techdocs-disabled #frequency: { minutes: 30 }
              #if-aws-techdocs-disabled frequency: { minutes: 1 }
              #if-aws-techdocs-disabled # supports ISO duration, "human duration" as used in code
              #if-aws-techdocs-disabled timeout: { minutes: 3 }
              #if-aws-techdocs-disabled initialDelay: { seconds: 15 }
    auth:
      environment: default
      session:
        secret: ${BACKEND_SECRET}
      providers:
        oidc:
          default:
    #        metadataUrl: <keycloak_base_url>/realms/rhdh/.well-known/openid-configuration # ${AUTH_OIDC_METADATA_URL}
            metadataUrl: https://demo-keycloak-instance.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com/realms/rhdh/.well-known/openid-configuration # ${AUTH_OIDC_METADATA_URL}
            clientId: rhdh-client # ${AUTH_OIDC_CLIENT_ID}
            clientSecret: 7iKyQUwyApIojzOlSj82vUWIhejv41E5 # ${AUTH_OIDC_CLIENT_SECRET}
            prompt: auto # ${AUTH_OIDC_PROMPT} # recommended to use auto
            ## uncomment for additional configuration options
            # callbackUrl: ${AUTH_OIDC_CALLBACK_URL}
            # tokenEndpointAuthMethod: ${AUTH_OIDC_TOKEN_ENDPOINT_METHOD}
            # tokenSignedResponseAlg: ${AUTH_OIDC_SIGNED_RESPONSE_ALG}
            # scope: ${AUTH_OIDC_SCOPE}
            ## Auth provider will try each resolver until it succeeds. Uncomment the resolvers you want to use to override the default resolver: `emailLocalPartMatchingUserEntityName`
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
            #    - resolver: emailMatchingUserEntityProfileEmail
            #    - resolver: emailLocalPartMatchingUserEntityName
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: argoInstance1
              url: https://argocd-instance-server-demo-project.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com
              username: admin 
              password: ${RHDH_ARGOCD_ADMIN_PWD}
    jenkins:
      instances:
        - name: default-jenkins
          baseUrl: https://jenkins-demo-project.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com/
          username: admin
          apiKey: 11c966b27ea87605758ccff451dc4cc4d2
    kubernetes:
      clusterLocatorMethods:
        - clusters:
            - authProvider: serviceAccount
              name: local-cluster
              # TODO automatically replace
              serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Imd3dzRNRWlCSFhTdnFMaGRoenBnLXJTT1BKVWtCcjMzVXpMTFUzVDdtUXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjIl0sImV4cCI6MTcyNjY5Mjg4MSwiaWF0IjoxNzI2Njg5MjgxLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMiLCJrdWJlcm5ldGVzLmlvIjp7Im5hbWVzcGFjZSI6ImRlbW8tcHJvamVjdCIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJwaXBlbGluZSIsInVpZCI6IjA0MGMxODYxLWM4NDUtNGVlZS1iZWY3LTI5ZTI0NDMwZGQ5NCJ9fSwibmJmIjoxNzI2Njg5MjgxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnBpcGVsaW5lIn0.QDNIBi1HIQgDW6NdBt6oFVza5dhDO-5pw9mxXX2mghLoSiEOGn3E4JqqDHZnjx2O3kgfRyIS8F3WKVlfawgPiv0c4R0ShxClWJ7ANxPflPpUiiWItx2cYBj-FBY7wT9bpGwTes5vpKeSb8pMZ_YPvHAtg5yAXif7tztzxd-1PRe6ipkv7_VzPWYoqiYhklLYox3sItu5mghXwhNVP63EKpTXBqL96qCW6WRGSWiQQEX9GfKP-ca6QXnUXSojxGr2xHlVj-1ezqrOp7AhNBPj6D5iDldzgNCvRgJyxp7sFpr7TffqTN26ByR6OmsEb90E6DHpN4gSGIePH0BHKVHe32qVuuHWWyUe71EHxh-8YKDHsxyqB3E-J6HEZAZoo09F3DW06Pioh5cdniRF0fsyOA2-mmNQeVz71pKZ5wkP5aj1voeNY0UOo2HSNmu7BkximckJ_Y9vpaEGjC6abhq3U8A_h6ghz4a3mGWaE3FrA9X7UYFgd1wK5NMT3TvXKvEkwmwOJ4lPMlpfbw1v891vFHMoL4T8f_zCedGuh3wwlM5rTv2duir2IosMoUr1VaL-IJEx2ZdirjHGfUaGhe40Q-uNXW7FVFHz4d2SNwaNyPirefhL-GYkn6_2KBgcHKCwqnipm7bPyePPlmVqgUATS765eWeSKkf6ro-d7Vu5XtI
              skipTLSVerify: true
              url: https://api.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com:6443
          type: config
      customResources:
        - apiVersion: v1beta1
          group: tekton.dev
          plural: pipelineruns
        - apiVersion: v1beta1
          group: tekton.dev
          plural: taskruns
        - apiVersion: v1
          group: route.openshift.io
          plural: routes
      serviceLocatorMethod:
        type: multiTenant
    dynamicPlugins:
      frontend:
        internal.backstage-plugin-simple-chat:
          entityTabs:
            # Adding a new tab
            - path: /dynamic-plugin-1
              title: Dynamic Plugin 1
              mountPoint: entity.page.dynamic-plugin-1
          appIcons:
            - name: chatIcon
              importName: ChatIcon
          mountPoints:
            - mountPoint: entity.page.ci/cards
              importName: SimpleChatPage
              config:
                layout:
                  gridColumn: '1 / -1'
            - mountPoint: entity.page.dynamic-plugin-1/cards
              importName: SimpleChatPage
              config:
                layout:
                  gridColumn: '1 / -1'
          dynamicRoutes:
            - path: /simple-chat
              importName: SimpleChatPage
              menuItem:
                text: 'Simple Chat'
                icon: chatIcon
    #if-minio-techdocs-disabled techdocs:
      #if-minio-techdocs-disabled builder: external
      #if-minio-techdocs-disabled generator:
        #if-minio-techdocs-disabled runIn: local
      #if-minio-techdocs-disabled publisher:
        #if-minio-techdocs-disabled type: 'awsS3'
        #if-minio-techdocs-disabled awsS3:
          #if-minio-techdocs-disabled bucketName: minio-tech-docs
          #if-minio-techdocs-disabled credentials:
            #if-minio-techdocs-disabled accessKeyId: minioadmin
            #if-minio-techdocs-disabled secretAccessKey: minioadmin
          #if-minio-techdocs-disabled region: eu-west-3
          #if-minio-techdocs-disabled endpoint: https://minio-api-demo-project.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com
          #if-minio-techdocs-disabled s3ForcePathStyle: true
          #if-minio-techdocs-disabled sse: 'AES256'
      #if-minio-techdocs-disabled cache:
        #if-minio-techdocs-disabled # Represents the number of milliseconds a statically built asset should
        #if-minio-techdocs-disabled # stay cached. Cache invalidation is handled automatically by the frontend,
        #if-minio-techdocs-disabled # which compares the build times in cached metadata vs. canonical storage,
        #if-minio-techdocs-disabled # allowing long TTLs (e.g. 1 month/year)
        #if-minio-techdocs-disabled # ttl: 3600000
        #if-minio-techdocs-disabled ttl: 60000

        #if-minio-techdocs-disabled # (Optional) The time (in milliseconds) that the TechDocs backend will wait
        #if-minio-techdocs-disabled # for a cache service to respond before continuing on as though the cached
        #if-minio-techdocs-disabled # object was not found (e.g. when the cache sercice is unavailable). The
        #if-minio-techdocs-disabled # default value is 1000
        #if-minio-techdocs-disabled readTimeout: 500
    #if-aws-techdocs-disabled techdocs:
      #if-aws-techdocs-disabled builder: external
      #if-aws-techdocs-disabled generator:
        #if-aws-techdocs-disabled runIn: local
      #if-aws-techdocs-disabled publisher:
        #if-aws-techdocs-disabled type: 'awsS3'
        #if-aws-techdocs-disabled awsS3:
          #if-aws-techdocs-disabled bucketName: redhat-demo-dev-hub-1
          #if-aws-techdocs-disabled credentials:
            #if-aws-techdocs-disabled accessKeyId: ${RHDH_AWS_S3_TECHDOCS_ACCESS_KEY_ID}
            #if-aws-techdocs-disabled secretAccessKey: ${RHDH_AWS_S3_TECHDOCS_SECRET_ACCESS_KEY}
          #if-aws-techdocs-disabled region: eu-west-3
          #if-aws-techdocs-disabled s3ForcePathStyle: true
          #if-aws-techdocs-disabled sse: 'AES256'
      #if-aws-techdocs-disabled cache:
        #if-aws-techdocs-disabled # Represents the number of milliseconds a statically built asset should
        #if-aws-techdocs-disabled # stay cached. Cache invalidation is handled automatically by the frontend,
        #if-aws-techdocs-disabled # which compares the build times in cached metadata vs. canonical storage,
        #if-aws-techdocs-disabled # allowing long TTLs (e.g. 1 month/year)
        #if-aws-techdocs-disabled # ttl: 3600000
        #if-aws-techdocs-disabled ttl: 60000

        #if-aws-techdocs-disabled # (Optional) The time (in milliseconds) that the TechDocs backend will wait
        #if-aws-techdocs-disabled # for a cache service to respond before continuing on as though the cached
        #if-aws-techdocs-disabled # object was not found (e.g. when the cache sercice is unavailable). The
        #if-aws-techdocs-disabled # default value is 1000
        #if-aws-techdocs-disabled readTimeout: 500
    
