kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: demo-project
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic 
        # documentation: https://janus-idp.io/plugins/keycloak
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        # documentation: https://backstage.io/docs/integrations/github/discovery/
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/0.1/html/argocd_plugin_for_backstage/argocd-plugin-for-backstage#installation
        # documentation: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/configuring_plugins_in_red_hat_developer_hub/rhdh-installing-dynamic-plugins#enabling-argo-cd-plugin
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-argocd
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-tekton
        # documentation: https://docs.redhat.com/en/documentation/red_hat_plug-ins_for_backstage/1.0/html-single/tekton_plugin_for_backstage/index#setting-tekton-plugin
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        # documentation: https://backstage.io/docs/features/kubernetes/configuration/#config
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-jenkins-backend-dynamic
        # documentation: https://www.npmjs.com/package/@backstage-community/plugin-jenkins-backend
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-jenkins
        disabled: false
      - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-3scale-backend-dynamic
        disabled: false
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-simple-chat-backend-dynamic-0.1.0.tgz'
        disabled: false
        integrity: 'sha512-JZovfAOgWfOggEiKZdnGe2MThwckjqcI6O/D3eEjn/nvVn9SEiZFc1wYx1DJoTRzs9sh/RS3+Pe81YfS9inDaw==' #backend-hash
      - package: 'http://plugin-registry:8080/internal-backstage-plugin-simple-chat-dynamic-0.1.0.tgz' 
        disabled: false
        integrity: 'sha512-uXXYsyMGii3/qxHtqATIxGjiGZSxh7HwqsT0Ji4uykcTAO5Ecmw6XOIDLI6R8nQeq6Fzfo6IFFpkAr9/ePjCiQ==' #frontend-hash
      #if-minio-techdocs-disabled - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/configuration/
        #if-minio-techdocs-disabled # doc discovery: https://backstage.io/docs/integrations/aws-s3/discovery/
        #if-minio-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/how-to-guides/
        #if-minio-techdocs-disabled # iframes in techdocs: https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates
        #if-minio-techdocs-disabled disabled: false
        #if-minio-techdocs-disabled pluginConfig: {}
      #if-aws-techdocs-disabled - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-backend-dynamic
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/configuration/
        #if-aws-techdocs-disabled # doc discovery: https://backstage.io/docs/integrations/aws-s3/discovery/
        #if-aws-techdocs-disabled # documentation: https://backstage.io/docs/features/techdocs/how-to-guides/
        #if-aws-techdocs-disabled # iframes in techdocs: https://backstage.io/docs/features/techdocs/how-to-guides/#how-to-add-the-documentation-setup-to-your-software-templates
        #if-aws-techdocs-disabled disabled: false
        #if-aws-techdocs-disabled pluginConfig: {}
#      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic TODO enable when you want to sync...
#                                                                                                   TODO ...users and groups from GitHub
#        disabled: false
#        pluginConfig: {}
