apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-cert-production
  namespace: cert-manager-operator
spec:
  secretName: my-cert-tls-production
  issuerRef:
    name: letsencrypt-prod  # or letsencrypt-staging
    kind: ClusterIssuer
  commonName: apps.cluster-bnc5t.sandbox3269.opentlc.com
  dnsNames:
    - apps.cluster-bnc5t.sandbox3269.opentlc.com
    - www.apps.cluster-bnc5t.sandbox3269.opentlc.com
  acme:
    config:
      - http01:
          ingress:
            class: nginx
        domains:
          - apps.cluster-bnc5t.sandbox3269.opentlc.com
          - apps.cluster-bnc5t.sandbox3269.opentlc.com
