apiVersion: v1
kind: Secret
metadata:
  name: tenant-secret
  namespace: test2
type: Opaque
stringData:
  # !! be careful: This needs to be empty and existing before creation of the tenant. Tenant creation will fill adminUrl and token field
#  adminURL: "https://demo-organization-maarten-5-admin.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com"
#  token: "b87464939a1579c71651251c7a3b64f4"