apiVersion: v1
kind: Secret
metadata:
  name: ecorp-admin-secret
  namespace: test2
type: Opaque
stringData:
  admin_password: averysecurepassword
---
apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: demo-organization-maarten-6
  namespace: test2
spec:
  masterCredentialsRef:
    name: system-seed
    namespace: test2
  passwordCredentialsRef:
    name: ecorp-admin-secret
    namespace: test2
  tenantSecretRef:
    name: tenant-secret
    namespace: test2
  email: maarten.vandeperre@redhat.com
  organizationName: Demo Organization maarten 6
  systemMasterUrl: 'https://master.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com'
  username: admin
# admin url becomes demo-organization-maarten-5-admin.apps.cluster-tqg9r.tqg9r.sandbox1273.opentlc.com/p/admin/dashboard