apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
  namespace: demo-project
spec:
  monitoring:
    enablePrometheusRules: true
    enabled: true
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: manual
  wildcardDomain: apps.cluster-djr6p.djr6p.sandbox1644.opentlc.com
