apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins-test
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
      securityRealm:
        local:
          allowsSignup: false
          users:
          - id: "admin"
            password: "rhdh"
          - id: "demo-user"
            password: "password"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      credentials:
        system:
          domainCredentials:
            - credentials:
                - usernamePassword:
                    scope: GLOBAL
                    id: demo-user-token
                    description: "Demo User API Token"
                    username: "demo-user"
                    password: "116e2b4d3be8a4ced881115370c7ab7c7a"
#      jobs:
#        - script: >
#            pipelineJob('demo-department/initial-pipeline') {
#                definition {
#                    cps {
#                        script('''
#                            pipeline {
#                                agent any
#                                stages {
#                                    stage('Echo') {
#                                        steps {
#                                            echo 'ok'
#                                        }
#                                    }
#                                }
#                            }
#                        '''.stripIndent())
#                        sandbox()
#                    }
#                }
#            }
#          sandbox: false
