apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
  namespace: demo-project
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: <secretvalue:TEKTON_GITHUB_USERNAME>
  password: <secretvalue:TEKTON_GITHUB_PERSONAL_ACCESS_TOKEN>
